[Feature] SMP-879: Publicar el módulo para usarlo como dependencia en el app
Quality-XP-Development-SESSA/sentinel-react-native-module pull request #1
Opened 2024-04-22 16:22 UTC by ArianaQ1

- Updated the react native plugin and added the android modules

2024-04-22 16:43 UTC, brodriguezQXD commented on android/src/main/AndroidManifestNew.xml
> +<manifest xmlns:android="http://schemas.android.com/apk/res/android">
Why is this *New required?

2024-04-24 12:43 UTC, ArianaQ1 commented on android/src/main/AndroidManifestNew.xml
> +<manifest xmlns:android="http://schemas.android.com/apk/res/android">
Done

2024-04-24 12:52 UTC, brodriguezQXD requested changes
Do we need the .yarn folder as part of the repo?

2024-04-24 13:05 UTC, brodriguezQXD approved these changes

2024-04-24 13:07 UTC, merged